language: node_js

git:
  depth: 5

addons:
  apt:
    packages:
      # This is required to run puppeteer (chrome) on linux/trusty
      - libnss3

node_js:
  - "8"
  - "10"
  - "12"

cache: npm

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" = "10" ]]; then npm run coveralls; fi
