# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install yarn
  - refreshenv
  - yarn install

build: off

test_script:
  - node --version && npm --version
  - npm test

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - node_modules -> package-lock.json
